---
title: "spotify_paper_script"
author: "Pablo Bello"
date: "11/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
####################
##### PACKAGES #####
####################
library(tidyverse)
library(dplyr)
library(cluster)
library(explor)
library(WVPlots)
library(parallel)
library(pbmcapply)
library(zoo)
library(lubridate)
library(ggthemes)
library(cowplot)
library(magrittr)
library(DescTools)
library(zetadiv)
library(betapart)
library(zetadiv)
library(ggrepel)
library(FactoMineR) 
library(factoextra)
library(RColorBrewer)
library(ggpubr)
library(knitr)
library(kableExtra)
library(data.table)
library(pbapply)
library(grid)
library(countrycode)
library(hrbrthemes)
library(ggsci)
library(scales)
library(vroom)
```


```{r}
########################################
####### DATA and general settings ######
########################################

#--- Itunes data
itunes <- vroom("itunes_data.csv.zip")

#---Spotify charts data
spotify_charts <- vroom("spotify_data.csv.zip")

#---Spotify features data
spotify_features <- vroom("spotify_features_data.csv")

#--- Pre-calculated z-diversity
z_df <- vroom("zeta_data.csv")


#--- Font Size for the paper
fsp <- 24
```



```{r}
##################################################################
####### DISTRIBUTION OF COUNTRIES IN WHICH A SONG CHARTED ######
#################################################################


#--- Number of countries and streams of song
n_countries_charted <- 
  spotify_charts %>% 
  group_by(track_id) %>% 
  summarise(countries = n_distinct(country), streams = sum(streams), .groups = 'drop')
  

#--- Percentage of streams by the number of countries in which songs charted
n_countries_charted_2 <- 
  n_countries_charted %>% 
  group_by (countries) %>% 
  mutate( group_streams = sum(streams)) %>% 
  ungroup () %>% 
  mutate (perc = group_streams / sum(streams))



#---Annotation
line_text <- grobTree(textGrob("[%] streams", x=0.65,  y=0.3, hjust=0,
  gp=gpar(col='#1DB954', fontsize= fsp)))


###### Figure 1 #####
#---Plot
plot_alpha <- n_countries_charted_2 %>% 
  ggplot (aes(countries))+
  geom_histogram (aes(y = ..density..), color = '#191414' , fill = '#191414') +
  geom_point (aes (countries, perc) , size = 0.8, color = '#1DB954') +
  geom_line (aes (countries, perc), color = '#1DB954') +
  scale_x_continuous(breaks = c(1,20,40,60)) +
  theme_pubr() +
  labs (y = "Density", 
        x = "Number of countries") +
  annotation_custom(line_text)
  

```

```{r}
###################################
####### ORIGIN OF THE SONGS  ######
##################################

global_imports <- 
  spotify_charts %>% 
  mutate(imported = ifelse (origin_song != country,1,0)) %>% 
  group_by (date, country) %>% 
  summarise (perc_imp = sum(imported, na.rm = TRUE) / n(), n() , .groups = 'drop') %>% 
  group_by(date) %>% 
  summarise(mean_imp = mean(perc_imp), sd = sd(perc_imp),n = n(), .groups = 'drop')


#--- Global Percentage of imported songs   
plot_beta <- 
  global_imports %>%
  mutate(mean_imp = rollmean(mean_imp, k =  10, fill = NA),
         sd = rollmean(sd, k = 10, fill = NA)) %>% 
  ggplot(aes(date, mean_imp)) +
  geom_line(color = '#1DB954') +
  scale_y_continuous (labels = number_format(accuracy = 0.01)) +
  theme_pubr() +
  labs (x = "")

```



```{r}
###################################################
####### SONG DIVERSITY ON ITUNES AND SPOTIFY ######
###################################################

#--- Vector with the countries on each dataset
itunes_countries <- itunes %>% distinct(country) %>% pull()
spotify_countries <- spotify_charts %>% distinct(country) %>% pull()
intersection <- intersect(itunes_countries, spotify_countries)

#--- Richness on Itunes 
diversity_itunes <- itunes %>%
  filter(country %in% spotify_countries) %>% #---Intersection of countries on both datasets
  group_by(date) %>% 
  summarise(unique = n_distinct(track), n = n(), .groups = 'drop') %>% 
  mutate(diversity = unique/n) 

#--- Richness on Spotify 
diversity_spotify <- 
  spotify_charts %>% 
  filter(country %in% itunes_countries) %>% #---Intersection of countries on both datasets
  group_by(date) %>% 
  summarise(unique = n_distinct(track_id), n = n(), .groups = 'drop') %>% 
  mutate(diversity = unique/n)


 
#--- Binding the datasets (lengthwise)
richness <-  bind_rows(Spotify  = diversity_spotify,
                             Itunes= diversity_itunes,
                             .id = "source") 

#--- Plot
plot_1 <- 
  richness %>% 
  mutate (diversity = rollmean(x = diversity, k = 10,  fill = NA)) %>% 
  ggplot(aes(date,diversity, group = source, color = source))+
  geom_line() +
  labs (y = "", 
        x = "",
        title = "Song Richness",
        color = "") +
  scale_color_manual(values = c('#D948DD', '#1DB954')) +
  theme_pubr (legend = c(0.15,0.8)) +
  theme(plot.title = element_text(hjust = 0.5))

```




```{r}
######################################################
####### DIVERSITY OF SONGS ON SPOTIFY  ###############
######################################################

#--- Diversity of songs
div_top200 <- spotify_charts %>%
  group_by(date) %>% 
  summarise(unique = n_distinct(track_id), n = n(), .groups = 'drop') %>% 
  mutate(diversity = unique/n)

div_top50 <- spotify_charts %>%
  filter(position <= 50) %>% 
  group_by(date) %>% 
  summarise(unique = n_distinct(track_id), n = n(), .groups = 'drop') %>% 
  mutate(diversity = unique/n) 

div_top10 <- spotify_charts %>%
  filter(position <= 10) %>% 
  group_by(date) %>% 
  summarise(unique = n_distinct(track_id), n = n(), .groups = 'drop') %>% 
  mutate(diversity = unique/n)

#--- Merged tibble
div_tops <- 
  tibble (date = div_top200$date ,
        top200 = div_top200$diversity,
        top50 = div_top50$diversity,
        top10 = div_top10$diversity) %>% 
  pivot_longer(cols = -date, names_to = "top", values_to = "diversity")

#--- Plot
plot_2 <- 
div_tops %>% 
  group_by(top) %>% 
  mutate (diversity = rollmean(x = diversity, k = 10,  fill = NA)) %>% 
  ungroup () %>% 
ggplot(aes(date,diversity, color = top))+
  geom_line() +
  labs (title = "Diversity Songs",
        y = "", 
        x = "",
        color = "") +
  scale_color_viridis_d() +
  theme_pubr (legend =c(0.8,0.2)) +
  theme(plot.title = element_text(hjust = 0.5))

```


``` {r}
######################################################
####### DIVERSITY OF ARTISTS ON SPOTIFY  #############
######################################################

#--- Diversity of artists top 200
art_top200 <- spotify_charts %>%
  group_by(date) %>% 
  summarise(unique = n_distinct(artist), n = n(), .groups = 'drop') %>% 
  mutate(diversity = unique/n) 

#--- Diversity of artists top 50
art_top50 <- spotify_charts %>%
  filter(position <= 50) %>% 
  group_by(date) %>% 
  summarise(unique = n_distinct(artist), n = n(), .groups = 'drop') %>% 
  mutate(diversity = unique/n) 

#--- Diversity of artists top 10
art_top10 <- spotify_charts %>%
  filter(position <= 10) %>% 
  group_by(date) %>% 
  summarise(unique = n_distinct(artist), n = n(), .groups = 'drop') %>% 
  mutate(diversity = unique/n)

#--- Merged tibble
art_tops <- 
  tibble (date = art_top200$date ,
        top200 = art_top200$diversity,
        top50 = art_top50$diversity,
        top10 = art_top10$diversity) %>% 
  pivot_longer(cols = -date, names_to = "top", values_to = "diversity")


#--- Plot
plot_3 <- 
art_tops %>% 
  group_by(top) %>% 
  mutate (diversity = rollmean(x = diversity, k = 10,  fill = NA)) %>% 
  ungroup () %>% 
ggplot(aes(date,diversity, color = top))+
  geom_line() +
  scale_y_continuous (labels = number_format(accuracy = 0.01)) +
  labs (title = "Diversity Artists",
        y = "", 
        x = "",
        color = "") +
  scale_color_viridis_d() +
  theme_pubr (legend = c(0.15,0.8)) +
  theme(plot.title = element_text(hjust = 0.5))


```

``` {r}
##############################################
####### DIVERSITY OF LABELS ON SPOTIFY #######
#############################################

#--- Diversity of labels top 200
lab_top200 <- spotify_charts %>%
  group_by(date) %>% 
  summarise(unique = n_distinct(label_1), n = n(), .groups = 'drop') %>% 
  mutate(diversity = unique/n) 

#--- Diversity of labels top 50
lab_top50 <- spotify_charts %>%
  filter(position <= 50) %>% 
  group_by(date) %>% 
  summarise(unique = n_distinct(label_1), n = n(), .groups = 'drop') %>% 
  mutate(diversity = unique/n) 

#--- Diversity of labels top 10
lab_top10 <- spotify_charts %>%
  filter(position <= 10) %>% 
  group_by(date) %>% 
  summarise(unique = n_distinct(label_1), n = n(), .groups = 'drop') %>% 
  mutate(diversity = unique/n)

#--- Merged tibble
lab_tops <- 
  tibble (date = lab_top200$date ,
        top200 = lab_top200$diversity,
        top50 = lab_top50$diversity,
        top10 = lab_top10$diversity) %>% 
  pivot_longer(cols = -date, names_to = "top", values_to = "diversity")

#--- Plot
plot_4 <- 
lab_tops %>% 
  group_by(top) %>% 
  mutate (diversity = rollmean(x = diversity, k = 10,  fill = NA)) %>% 
  ungroup () %>% 
ggplot(aes(date,diversity, color = top))+
  geom_line() +
  scale_y_continuous (labels = number_format(accuracy = 0.01)) +
  labs ( title = "Diversity Labels",
    y = "",
    x = "",
    color = "") +
  scale_color_viridis_d() +
  theme_pubr (legend = c(0.15,0.8)) +
  theme(plot.title = element_text(hjust = 0.5))

```

``` {r}
####################################
######## GINI RECORD LABELS ######## 
####################################

#--- Gini top 200
gini_top200 <- 
  spotify_charts %>% 
  group_by (date) %>% 
  count (label_1, sort = TRUE) %>% 
  group_by (date) %>% 
  summarise(gini = Gini(n), .groups = 'drop')

#--- Gini top 50
gini_top50 <- 
  spotify_charts %>% 
  filter(position <= 50) %>% 
  group_by (date) %>% 
  count (label_1, sort = TRUE) %>% 
  group_by (date) %>% 
  summarise(gini = Gini(n), .groups = 'drop')

#--- Gini top 10
gini_top10 <- 
  spotify_charts %>% 
  filter(position <= 10) %>% 
  group_by (date) %>% 
  count (label_1, sort = TRUE) %>% 
  group_by (date) %>% 
  summarise(gini = Gini(n), .groups = 'drop')


#--- Merged tibble
gini_tops <- 
  tibble (date = gini_top200$date ,
        top200 = gini_top200$gini,
        top50 = gini_top50$gini,
        top10 = gini_top10$gini) %>% 
  pivot_longer(cols = -date, names_to = "top", values_to = "gini")

#--- Plot
plot_5 <- 
gini_tops %>% 
  group_by(top) %>% 
  mutate (gini = rollmean(x = gini, k = 10,  fill = NA)) %>% 
  ungroup () %>% 
ggplot(aes(date,gini, color = top))+
  geom_line() +
  scale_y_continuous (labels = number_format(accuracy = 0.01)) +
  labs (title = "Gini Labels",
    y = "",
    x = "",
    color = "") +
  scale_color_viridis_d() +
  theme_pubr (legend = c(0.15,0.2)) +
  theme(plot.title = element_text(hjust = 0.5))


```

```{r}
####################################
######## BETA DIVERSITY ############
####################################

#--- DATA PREPARATION ---#

#--- Dividing the dataframe by days and transforming the data into a wide format ---#
daily_charts <- spotify_charts %>% 
  select(country,track_id, date) %>% 
  group_split(date)


daily_charts_wide <- pblapply(daily_charts, function(chart){
 
chart_wide <- chart %>% 
  mutate(n = 1) %>% 
  pivot_wider(names_from = track_id, values_from = n, values_fn = list(n = min)) %>% 
  select (-date)
})




df_wide <- pblapply(daily_charts_wide , function (chart_wide){

df_wide <- setnafill(chart_wide[,-1], fill = 0) #--- Fill NAs with 0s
df_wide <- as.data.frame(df_wide) #---Transform into dataframe to be able to include rownames
rownames(df_wide) <- chart_wide$country #--- The rownmaes / ids
  
return (df_wide)
})

#---Assigning dates as names to the list of wide dfs
dates <- spotify_charts %>% arrange(date) %>% distinct(date) %>% pull ()
names(df_wide) <- dates


```

```{r}
###################################
######## JACCARD INDEX ############
###################################

jacc_index <- pblapply (df_wide, function(i){
  
matrix <- suppressMessages(philentropy::distance(i, method = "jaccard", use.row.names = TRUE,diag = FALSE,upper = FALSE))
df <- tibble(value = matrix[lower.tri(matrix)]) #---Extracting lower triangle from matrix(without diagonal)
return(df)

})


jacc_index_metrics <- mclapply(jacc_index, function(i) {
  i %>%  
    summarise (n = n (),mean =  mean(value), sd = sd (value)) %>% 
    mutate (se = sd / sqrt(n)) 
})

names(jacc_index_metrics) <- dates



plot_6 <-
   bind_rows(jacc_index_metrics, .id = "date") %>% 
  mutate(mean = rollmean(x = mean, k = 10,  fill = NA),
         date = as.Date(date)) %>% 
 ggplot(aes(date,mean, group = 'none'))+
  geom_line(color = '#1DB954') + 
  scale_y_continuous (labels = number_format(accuracy = 0.01)) +
   labs (y = "",
         x = "", 
         title = "Beta Diversity of Songs") +
   theme_pubr (legend = "none" ) +
  theme(plot.title = element_text(hjust = 0.5))
  
```



```{r}
###############################################################
######## MARKET SHARE FOR THE THREE BIGGEST LABELS ############
###############################################################


#--- The ten biggest labels all belong in one way or another to the big three (Warner, Sony and Universal)
big_3 <- spotify_charts %>%
  count (label_1, sort = TRUE) %>% 
  slice (1:10) %>% 
  pull(label_1) 


#--- Market share top 200
share_top200 <- 
  spotify_charts %>% 
  mutate (label = as_factor(ifelse (label_1 %in% big_3 == TRUE,1, 0)),
          label = fct_recode(label , "Big_label" = "1" , "Others" = "0")) %>% 
  group_by (date) %>% 
  count(label) %>% 
  pivot_wider (names_from = label, values_from = n) %>% 
  mutate (perc_big_labels = Big_label / (Big_label + Others))

#--- Market share top 50
share_top50 <- 
  spotify_charts %>% 
  filter(position <= 50) %>% 
  mutate (label = as_factor(ifelse (label_1 %in% big_3 == TRUE,1, 0)),
          label = fct_recode(label , "Big_label" = "1" , "Others" = "0")) %>% 
  group_by (date) %>% 
  count(label) %>% 
  pivot_wider (names_from = label, values_from = n , ) %>% 
  mutate (perc_big_labels = Big_label / (Big_label + Others))

#--- Market share top 10
share_top10 <- 
  spotify_charts %>% 
  filter(position <= 10) %>% 
  mutate (label = as_factor(ifelse (label_1 %in% big_3 == TRUE,1, 0)),
          label = fct_recode(label , "Big_label" = "1" , "Others" = "0")) %>% 
  group_by (date) %>% 
  count(label) %>% 
  pivot_wider (names_from = label, values_from = n , ) %>% 
  mutate (perc_big_labels = Big_label / (Big_label + Others))
 
 
#--- Merge tibbles
share_tops <- tibble(date =  share_top200$date,
       top200 = share_top200$perc_big_labels,
       top50 = share_top50$perc_big_labels,
       top10 = share_top10$perc_big_labels) %>% 
  pivot_longer(cols = -date, names_to = "top", values_to = "share")


#--- Plot b

plot_7_b <- 
  share_top200 %>% 
  mutate(Indies = 1 - perc_big_labels) %>% 
  rename (`Big Three`= perc_big_labels) %>% 
  pivot_longer(cols = c(`Big Three`, Indies), names_to = "label" , values_to = "value") %>% 
  group_by (label) %>% 
  mutate(value = rollmean(value, k = 10 , fill = NA)) %>% 
  ggplot(aes(date, value, color = label)) +
  geom_line () +
  scale_y_continuous (labels = number_format(accuracy = 0.01)) +
  labs (title = "Market Share",
    x = "",
        y = "",
        color = "") +
  theme_pubr (legend =c(0.8,0.5)) +
  scale_colour_brewer(palette = "Set1") +
  theme(plot.title = element_text(hjust = 0.5))

```



  

```{r}
#########################################
####### INCIDENCE-BASED CLUSTERING ######
#########################################

#--- Yearly clusters of incidence based distance matrices

#--- DATA PREPARATION ---#

#---Unique country/year songs
yearly_charts <- 
  spotify_charts %>% 
  mutate(year = year(date)) %>% 
  group_by (year, country) %>% 
  distinct(track_id, .keep_all = TRUE)


#--- Dividing the dataframe by years and transforming the data into a wide format
yearly_charts_list <- yearly_charts %>% 
  select(country,track_id, year) %>%
  ungroup () %>% 
  group_split(year)

#--- Incidence-based matrix
yearly_charts_wide <- lapply(yearly_charts_list, function(chart){
  
  chart_wide <- chart %>% 
  mutate(n = 1) %>% 
  pivot_wider(names_from = track_id, values_from = n) %>% 
  select(-year) 
  
df_wide <- setnafill(chart_wide[,-1], fill = 0) #--- Fill NAs with 0s
df_wide <- as.data.frame(df_wide) #---Transform into dataframe to be able to include rownames
rownames(df_wide) <- chart_wide$country #--- The rownames / ids

  

return(df_wide)
  
})


#---Jaccard Index for yearly matrices and MDS
mds_year <- lapply (yearly_charts_wide, function(i){

matrix <- philentropy::distance(i, method = "jaccard", use.row.names = TRUE,diag = FALSE,upper = FALSE)
mds_years <- cmdscale(matrix) #---Multidimensional Scaling on the distance matrix
mds_df <- as_tibble(mds_years , rownames = "country" )

return(mds_df)
})



#--- Dataframe with rownames (for clustering)

cl_df <-lapply (mds_year, function (df){

cl_df <- df  %>% select (-country)
cl_df <- as.data.frame(cl_df)
rownames(cl_df) <- df$country
 
return (cl_df) 
})



```



``` {r}
############################
##### Visualizing MDS #####
###########################

mds_df <- bind_rows (mds_year, .id = "year") %>% 
  mutate(year = as_factor(year),
         year =fct_recode(year, "2017" = "1", "2018" = "2" , "2019" = "3" , "2020"= "4"),
         continent = countrycode (sourcevar = country,
                            origin = "country.name",
                            destination = "continent"))



plot_clusters <-  mds_df  %>% 
ggplot(aes(V1, V2 ,label = country,color = continent)) +
  geom_point (size = 2.5) +
     facet_wrap(~ year) +
     labs (x = "" , 
           y = "", 
           color = "") +
  scale_color_tron() +
   theme_pubr(border = TRUE,legend = "bottom") +
     theme(panel.grid.major.x = element_blank(), 
       panel.grid.minor.x = element_blank(),
       panel.grid.major.y = element_blank(),
       panel.grid.minor.y = element_blank(),
       strip.background = element_rect(colour="white", fill="white"))
  
plot_clusters_labs <-  plot_clusters + 
  geom_text_repel(
    data = subset(mds_df, country == "United States" | country == "Spain" | country == "Turkey" | country == "Canada" | country == "Brazil"),
    force = 0.5,
    segment.alpha = 0.7,
    size = 9,
    show.legend = FALSE) +
  theme(strip.text = element_text(size= fsp))

```



```{r}
##########################
##### ZETA DIVERSITY #####
##########################

#--- Plot

#--- Log-log
plot_z <- z_df %>%
  filter(order != 1) %>%  #-- filter out zeta diversity of order 1
  ggplot(aes(order, mean, color = month, group = month)) +
  geom_line () +
  scale_color_viridis_c(breaks = c(1,13,25,37), labels = c('2017','2018','2019', '2020')) + 
  scale_y_log10 () +
  scale_x_log10(
    breaks = c(3,5,10,20),
   labels = c(3,5,10,20)) + 
  annotation_logticks() +
  labs (color = "Month",
        x = "Order",
        y = "Z-value") +
   theme_pubr() +
guides(color = guide_colourbar (direction = "horizontal", barwidth = 15 , barheight  = 0.7, title.vjust = 1))


  
#---Regression 
zeta_div_reg <-
  z_df %>% 
  mutate(log10_order = log10(order),
         log10_order = order - mean (order),
         month = month - mean(month)) 
  
         
model_1 <- lm (formula = log10(mean) ~ log10_order + month + month*log10_order, data = zeta_div_reg )

reg_table_2 <- stargazer::stargazer(model_1,type = "latex", out ="reg_table.tex" )

```






```{r}
#####################################
####### FEATURE-BASED DISTANCE ######
#####################################


#--- Dividing the tibble by days 
days <- 
  spotify_features %>% 
  group_by(date) %>% 
  group_split()


#--- Tibble with rownames
features_daily <- mclapply(days, function(i){
  
chart_numeric <- i %>% select (-country, -date)
chart_numeric <- as.data.frame(chart_numeric)
rownames(chart_numeric) <- i$country
names(chart_numeric) <- i[["date"]][[1]] # Name the data-frame with the date
return(chart_numeric)
  
})


#-- Euclidean distances 
euclidean_metrics <- lapply (features_daily, function(i){
date <- names(i)[1]
matrix <- dist(i, method = "euclidean")
n <- dim(as.matrix(matrix))[1]
N <- n * (n - 1) /2 #Number of elements on the lower triangle of the matrix
df <- tibble (n = N, mean = mean(matrix) , sd = sd(matrix), date = date) %>% 
   mutate (se = sd / sqrt(n))

return(df)
})


euclidean_df <- bind_rows(euclidean_metrics) %>% 
  relocate(date) %>% 
  mutate(date = as.Date(date)) %>% 
  arrange(date)


christmas <- c("2017-12-25", "2018-12-25","2019-12-25")



plot_e <- euclidean_df %>% 
mutate (mean = rollmean(x = mean, k = 10,  fill = NA)) %>%
ggplot(aes(date, mean))+
  geom_line() +  
  geom_vline(xintercept = as.Date(christmas), color = "red") +
  labs (y = "Mean euclidean distance",
    x = "") +
  theme_pubr()


```


```{r}

####################
##### FIGURES #####
###################

###### THEMES for the figures ######

#--- For figures with both axes
theme_figures_1 <- theme (axis.title.y = element_text(size= fsp),
                                 legend.text = element_text(size=fsp),
                                 axis.text.x = element_text(size = fsp),
                                 axis.text.y = element_text(size = fsp))

#--- For figures with just the y-axis
theme_figures_2 <- theme (axis.title.y = element_text(size= fsp),
                                 legend.text = element_text(size=fsp),
                                 axis.text.y = element_text(size = fsp),
                                 axis.text.x = element_blank())

##############################################
figure_1 <- plot_alpha + theme_figures_1 + theme (axis.title.x = element_text(size = fsp))

save_plot (filename = "figure_1.png" , figure_1, base_height = 3.71*2)


##############################################
figure_2 <- plot_clusters_labs + theme_figures_1

save_plot(filename = "figure_2.png" , plot = figure_2, base_height = 3.71*3)


##############################################
figure_3 <- plot_1 + labs(y = "Song richness", title = "") + theme_figures_1
save_plot(filename = "figure_3.png", figure_3, base_height = 3.71*2)


##############################################
figure_4 <- plot_grid (
  plot_beta + 
    labs(y = "[%] Song imports") +
    theme_figures_2,
  
  plot_6 + 
    labs (title = "" , 
          y = expression(paste(beta, " songs"))) + 
    theme_figures_1,
  
 
  nrow = 2,labels = "auto",label_fontface = "bold",label_size = fsp)

save_plot(filename = "figure_4.png", figure_4,base_height = 3.71*3, base_asp = 1)


##############################################
figure_5 <- plot_grid (
  plot_3 + 
    labs (title = "" , y = "Artist richness") + 
    theme_figures_2, 
  plot_4 + 
    labs (title = "", y = "Label richness") + 
    theme_figures_1,
  labels = "auto",label_fontface = "bold",label_size = fsp, nrow = 2)

save_plot(filename = "figure_5.png", figure_5, base_height = 3.71*3,base_asp = 1)


##############################################
figure_6 <- plot_grid (
  plot_5 + labs (title = "", y = "Gini labels") + theme_figures_2,
  plot_7_b + labs (title = "", y = "Market share") + theme_figures_1,
  labels = "auto",label_fontface = "bold",label_size = fsp, nrow = 2
)

save_plot(filename = "figure_6.png", figure_6, base_height = 3.71*3,base_asp = 1)

##############################################
figure_7 <- plot_z + 
  theme (axis.title.y = element_text(size= fsp),
         axis.title.x = element_text(size = fsp),
         legend.text = element_text(size= 15),
         legend.title = element_text(size = fsp),
         axis.text.x = element_text(size = fsp),
         axis.text.y = element_text(size = fsp))

save_plot(filename = "figure_7.png", figure_7, base_height = 3.71*2)


##############################################
figure_8 <- plot_e +  theme_figures_1
save_plot(filename = "figure_8.png", figure_8, base_height = 3.71*2)


```


```{r}
####### Other Calculations ####### 
##### RATIO SONGS:ARTISTS:LABELS  BY YEAR #####
ratios <- 
  spotify_charts %>%
  mutate(year = year(date), month = month(date)) %>% 
  group_by(year) %>% 
  filter(month <= 6) %>% 
  summarise(songs = n_distinct(track_id), artists = n_distinct(artist), labels = n_distinct(label_1)) %>% 
  mutate(s_a = songs / artists , s_l = songs / labels , a_l = artists / labels) %>% 
  select(-songs, -artists , -labels)

```


